### ISSUE TITLE
Support for strip option

### ISSUE THREAD

**Issue by john-landgrave** [k2wanko/vulcanize-middleware#2]
The output I'm getting is breaking lines in the middle of comments, which is making the JavaScript embedded in the Polymer Elements invalid. I would be fine with just using the built-in strip option from Vulcanize, but it doesn't appear to be supported.

**Comment by john-landgrave** [comment]
I have this fixed, but I can't push to your repo. @k2wanko, if you'll allow me to push to your repo, I've added support for the strip and inline options and exposed them via the options object used in the app.use() statement.

**Comment by k2wanko** [comment]
@john-landgrave 

I'm not good at English.

Could you send me the code which improve my product by PullRequest? If you send me the code by Pull Request, I will Merge the code.

**Comment by john-landgrave** [comment]
@k2wanko, you need to enable permissions for anyone to push to your repository so that I can make the pull request, please. I see that you made a branch for this, but I get a "permission denied" error when I try to Git Push.

**Comment by k2wanko** [comment]
@john-landgrave Could you please Fork this repository and make a Pul Request you fixed?
